name: CI

on:
  push:
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List files
        run: ls -la  
