name: CI

on:
  push:
    branches:
      - work
    paths:
      - ansible/Dockerfile
  pull_request:
    branches:
      - work
    paths:
      - ansible/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List files
        run: ls -la  
