name: CI1

on:
  push:
    paths-ignore:
      - '**/Dockerfile'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: testcommand
      run: ls -la
