name: CI

on:
  push:
    branches:
      - main
    #paths:
    #- 'ansible/Dockerfile'  
  pull_request:
    branches:
      - main
    #paths:
    #  - 'ansible/Dockerfile'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    #- name: show Dockerfile
    #  working-directory: ansible
    #  run: cat Dockerfile
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
       python-version: 3
        
    - name: Install dependencies
      run: pip install ansible  
      
    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install -y unzip
      
    - name: install Packer
      run: |
          wget https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
          unzip packer_1.7.0_linux_amd64.zip
          sudo mv packer /usr/local/bin/
    
    - name: packer test command 
      run: packer --version 
    
    - name: ansible test command 
      run: ansible --version 
    
    - name: aws cli test command 
      run: aws ec2 describe-instances 
       
    - name: terraform init test command  
      working-directory: terraform
      run: terraform init
        
    - name: terraform plan test command  
      working-directory: terraform
      run: terraform plan 
